inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - Rakefile

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  CountComments: false
  Max: 100

Documentation:
  Enabled: false

LineLength:
  Enabled: true
  Max: 120

MethodLength:
  CountComments: false
  Max: 10

ParameterLists:
  Max: 4
  CountKeywordArgs: true

TrailingWhitespace:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
